image: docker:latest

variables:
  IMAGE_NAME: registry.gitlab.com/ripitchip/new-portfolio
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build
  - dockerize

build:hugo:
  image: docker:stable
  stage: build
  script:
    # Build image using Dockerfile.build, output static site as artifact
    - docker build -f docker/Dockerfile.build -t hugo-builder .
    - docker create --name extract hugo-builder
    - docker cp extract:/src/public ./public
    - docker rm -f extract
  artifacts:
    paths:
      - public/
    expire_in: 1 hour

docker:build-and-push:
  stage: dockerize
  dependencies:
    - build:hugo
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - mkdir -p docker/public
    - cp -r public/* docker/public/
    - docker build -f docker/Dockerfile.nginx -t "$IMAGE_NAME:latest" docker/
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
