stages:
  - build
  - dockerize

variables:
  HUGO_ENV: production

build:
  stage: build
  image:
    name: klakegg/hugo:ext-alpine
    entrypoint: [""]
  before_script:
    - git submodule update --init --recursive
  script:
    - hugo --minify
  artifacts:
    paths:
      - public/
    expire_in: 1h
  only:
    - main

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    # Use root context, but point to docker/Dockerfile
    - docker build -f docker/Dockerfile -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - main
