image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: registry.gitlab.com/ripitchip/new-portfolio
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - dockerize

# Step 1: Build the Hugo site
build:hugo:
  image: hugomods/hugo:nightly
  stage: build
  before_script:
    - git submodule update --init --recursive
    - mkdir -p layouts/partials
    - echo '{{/* fallback for analytics */}}' > layouts/partials/google_analytics.html
  script:
    - hugo --minify
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
  only:
    - main

# Step 2: Dockerize and push the site
docker:build-and-push:
  stage: dockerize
  dependencies:
    - build:hugo
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - mv public docker/public
    - docker build -t "$IMAGE_NAME:latest" -f docker/Dockerfile docker/
    - docker push "$IMAGE_NAME:latest"
  only:
    - main
